services:
  database:
    image: postgres:16-alpine
    ports:
      - ${DB_PORT:-5432}:5432
    healthcheck:
      test: pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: